// BlueprintGeneratedClass Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C
// Size: 0x1c2 (Inherited: 0xd8)
struct UComp_GameMode_ShootingRangeInteractionTracker_C : UActorComponent {
	struct FPointerToUberGraphFrame UberGraphFrame; // 0xd8(0x08)
	struct TMap<enum class Enum_ShootingRangeModule, struct FRangeModuleInteractionResults> ModuleInteractionResults; // 0xe0(0x50)
	struct FShootingRangeSettings ShootingRangeSettings; // 0x130(0x14)
	char pad_144[0x4]; // 0x144(0x04)
	struct AAimBotsManager_C* AimbotsManager; // 0x148(0x08)
	enum class Enum_ShootingRangeModule CurrentlyEngagedModule; // 0x150(0x01)
	char pad_151[0x7]; // 0x151(0x07)
	struct FTimerHandle CurrentlyEngagedModuleIdleTimer; // 0x158(0x08)
	double CurrentlyEngagedModuleStartTime; // 0x160(0x08)
	bool IsCurrentlyEngagedInModule; // 0x168(0x01)
	char pad_169[0x7]; // 0x169(0x07)
	struct TMap<enum class Enum_ShootingRangeModule, double> ModuleEngagementTimeouts; // 0x170(0x50)
	bool DisplayDebug; // 0x1c0(0x01)
	enum class Enum_RangeModuleInteractionTag StationaryBotDistance; // 0x1c1(0x01)

	void RecordEvents(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.RecordEvents // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void GetTagForTargetDistance(int32_t TargetDistance, enum class Enum_RangeModuleInteractionTag& Tag); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.GetTagForTargetDistance // (Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void End Engagement if Actively Engaged(enum class Enum_ShootingRangeModule ModuleID); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.End Engagement if Actively Engaged // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void IsEngagedWithModule(enum class Enum_ShootingRangeModule ModuleID, bool& Result); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.IsEngagedWithModule // (Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void DebugInteractions(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.DebugInteractions // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void ToggleDebugDisplay(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.ToggleDebugDisplay // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void AddToModuleTag(enum class Enum_ShootingRangeModule ModuleID, enum class Enum_RangeModuleInteractionTag Tag, double Amount); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.AddToModuleTag // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void StartModuleEngagement(enum class Enum_ShootingRangeModule NewEngagedModule); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.StartModuleEngagement // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void EndCurrentModuleEngagement(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.EndCurrentModuleEngagement // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void UpdateCurrentlyEngagedModule(enum class Enum_ShootingRangeModule NewEngagedModule); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.UpdateCurrentlyEngagedModule // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void GetModuleEngagementTimeout(enum class Enum_ShootingRangeModule Module, bool& HasTimeout, double& Timeout); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.GetModuleEngagementTimeout // (Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetInteractionDebugString(struct FRangeModuleInteractionResults& Interaction, struct FString& DebugString); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.GetInteractionDebugString // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void IncrementModuleTag(enum class Enum_ShootingRangeModule ModuleID, enum class Enum_RangeModuleInteractionTag Tag); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.IncrementModuleTag // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void GetActiveAimbotModuleID(enum class Enum_ShootingRangeModule& ModuleID); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.GetActiveAimbotModuleID // (Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void Add to Interaction Tag(struct FRangeModuleInteractionResults& ModuleInteraction, enum class Enum_RangeModuleInteractionTag Tag, double ValueToAdd); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.Add to Interaction Tag // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void GetAimBotsManager(struct AAimBotsManager_C*& AimbotsManager); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.GetAimBotsManager // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void ShootingRangeSettingsUpdated(struct FShootingRangeSettings ShootingRangeSettings); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.ShootingRangeSettingsUpdated // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void GetShootingRangeSettings(struct FShootingRangeSettings& Settings); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.GetShootingRangeSettings // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void SaveModuleInteraction(enum class Enum_ShootingRangeModule Module, struct FRangeModuleInteractionResults Interaction); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.SaveModuleInteraction // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void GetModuleInteraction(enum class Enum_ShootingRangeModule Module, struct FRangeModuleInteractionResults& ModuleInteractions); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.GetModuleInteraction // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void RecordAimbotChallengeStart(enum class Enum_ShootingRangeModule Module, enum class Enum_ShootingRangeModuleDifficulty Difficulty, bool WithArmor); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.RecordAimbotChallengeStart // (Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void ReceiveBeginPlay(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.ReceiveBeginPlay // (Event|Public|BlueprintEvent) // @ game+0x19be2f0
	void OnGameStateLevelStreamingComplete(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnGameStateLevelStreamingComplete // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnAimbotChallengeSequenceStarted(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnAimbotChallengeSequenceStarted // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void BindToAimBotsManager(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.BindToAimBotsManager // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnAimbotChallengeAborted(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnAimbotChallengeAborted // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnAimbotChallengeCompleted(int32_t Score); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnAimbotChallengeCompleted // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnAimbotChallengeBotKilled(struct UDamageResponse* DamageResponse); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnAimbotChallengeBotKilled // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnAimbotPracticeBotKilled(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnAimbotPracticeBotKilled // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnAimbotPracticeBotsReset(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnAimbotPracticeBotsReset // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void BindToSprayWall(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.BindToSprayWall // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnSprayWallBotDamaged(struct AActor* DamagedActor, float Damage, struct UDamageType* DamageType, struct AController* InstigatedBy, struct AActor* DamageCauser); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnSprayWallBotDamaged // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnSprayWallTargetDamaged(struct UDamageResponse* Response); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnSprayWallTargetDamaged // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnSprayWallTargetBotActiveChanged(bool NewIsActive, struct ATargetPracticeTrainingBot_C* BOT); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnSprayWallTargetBotActiveChanged // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void BindToFlyingDrones(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.BindToFlyingDrones // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnFlyingDroneTriggerDestroyed(struct UDamageResponse* Response); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnFlyingDroneTriggerDestroyed // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnFlyingDroneSpawned(struct AActor* SpawnedActor); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnFlyingDroneSpawned // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnFlyingDroneKilled(struct UDamageResponse* Response); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnFlyingDroneKilled // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void BindToPlantModule(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.BindToPlantModule // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void BindToDefuseModule(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.BindToDefuseModule // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnPlantModuleStart(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnPlantModuleStart // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnPlantModuleBotKilled(struct AShooterCharacter* Victim); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnPlantModuleBotKilled // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnPlantModuleFinished(enum class Enum_PracticeModuleResult Result); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnPlantModuleFinished // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnDefuseModuleStart(); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnDefuseModuleStart // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnDefuseModuleEnd(enum class Enum_PracticeModuleResult Result); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnDefuseModuleEnd // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnDefuseModuleBotKilled(struct AShooterCharacter* Victim); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnDefuseModuleBotKilled // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnSprayWallRangeSwitchHit(struct AShootable_Switch_Spray_Wall_C* SwitchAction); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnSprayWallRangeSwitchHit // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnSprayWallImpactClearSwitchHit(struct AShootable_Switch_Impact_Clear_C* SWITCH); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnSprayWallImpactClearSwitchHit // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnSprayWallBotToggleSwitchHit(struct AShootable_Switch_TargetDummy_C* SWITCH); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnSprayWallBotToggleSwitchHit // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void OnGameStateRoundEnded(int32_t RoundNumberEnded); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.OnGameStateRoundEnded // (BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void ExecuteUbergraph_Comp_GameMode_ShootingRangeInteractionTracker(int32_t EntryPoint); // Function Comp_GameMode_ShootingRangeInteractionTracker.Comp_GameMode_ShootingRangeInteractionTracker_C.ExecuteUbergraph_Comp_GameMode_ShootingRangeInteractionTracker // (Final|UbergraphFunction|HasDefaults) // @ game+0x19be2f0
};

