// BlueprintGeneratedClass FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C
// Size: 0x30 (Inherited: 0x30)
struct UFunctionLibrary_NPE_AgentBot_C : UBlueprintFunctionLibrary {

	void ResetBotCharacterByTeam(struct TSoftClassPtr<UObject> Character, enum class EAresTeamRole Team, struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.ResetBotCharacterByTeam // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void ApplyPreventDeathFromDamageBuffToCharacter(struct TSoftClassPtr<UObject> CharacterClass, enum class EAresTeamRole Team, struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.ApplyPreventDeathFromDamageBuffToCharacter // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void SetBotForceMoveAndAim(struct TSoftClassPtr<UObject> CharacterClass, enum class EAresTeamRole Team, struct FVector MoveLocation, struct AActor* AimActor, struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.SetBotForceMoveAndAim // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void ReplenishResourceForMarkup(struct TSoftClassPtr<UObject> BotClass, enum class EAresTeamRole Team, struct AAIBehaviorMarkup* BehaviorMarkup, int32_t UnitsToReplenish, struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.ReplenishResourceForMarkup // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void SetBotBehaviorMarkup(struct TSoftClassPtr<UObject> BotClass, enum class EAresTeamRole Team, struct AAIBehaviorMarkup* BehaviorMarkup, struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.SetBotBehaviorMarkup // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void InitializeBot(struct AController_NPE_AgentBot_C* BotController, bool IsAllyBot, struct TMap<enum class EAresItemSlot, struct AAresItem*> InInventoryChanges, struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.InitializeBot // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void SaveBotResetInfo(struct TSoftClassPtr<UObject> BotClass, enum class EAresTeamRole Team, struct AActor* ResetPoint, struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.SaveBotResetInfo // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void SetBotHoldAngle(struct TSoftClassPtr<UObject> BotClass, enum class EAresTeamRole Team, struct AActor* HoldAngleTarget, struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.SetBotHoldAngle // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void AssignNPEAgentBotToRoomEntrance(struct TSoftClassPtr<UObject> BotClass, enum class EAresTeamRole Team, struct FString EntranceName, struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.AssignNPEAgentBotToRoomEntrance // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void SetBotFollowTarget(struct TSoftClassPtr<UObject> BotClass, enum class EAresTeamRole Team, struct AActor* FollowTarget, struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.SetBotFollowTarget // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void KillBotWithBot(struct TSoftClassPtr<UObject> KillerBotClass, enum class EAresTeamRole KillerTeam, struct TSoftClassPtr<UObject> KilledBotClass, enum class EAresTeamRole KilledTeam, struct UDamageType* DamageTypeClass, struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.KillBotWithBot // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void GetBotCharacterByTeam(struct TSoftClassPtr<UObject> CharacterClass, enum class EAresTeamRole Team, struct UObject* __WorldContext, struct ABasePlayerCharacter_C*& BotCharacter); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.GetBotCharacterByTeam // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void Get NPE Agent Bot Controller Helper(struct AShooterPlayerState* ShooterPlayerState, struct UObject* __WorldContext, struct AController_NPE_AgentBot_C*& NPE Agent Bot Controller); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.Get NPE Agent Bot Controller Helper // (Static|Private|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void Save Bot Team Reset Info(struct TArray<None>& ResetPoints, enum class EAresTeamRole TeamRole, struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.Save Bot Team Reset Info // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void Reset Bots On Team(enum class EAresTeamRole TeamRole, struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.Reset Bots On Team // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void Validate Team Role(struct AShooterPlayerState* ShooterPlayerState, enum class EAresTeamRole TeamRole, struct UObject* __WorldContext, bool& IsValid); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.Validate Team Role // (Static|Private|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void Set Bot Team Follow Target(struct AActor* FollowTarget, enum class EAresTeamRole TeamRole, struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.Set Bot Team Follow Target // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void Add Spatial Awareness Components(struct AShooterCharacter* InShooterCharacter, struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.Add Spatial Awareness Components // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void Get NPE Agent Bot Behavior Helper(struct AController_NPE_AgentBot_C* In Controller, struct UObject* __WorldContext, struct UBehaviorTree*& Out Behavior); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.Get NPE Agent Bot Behavior Helper // (Static|Private|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void Prepare NPE Agent Bots for Team Swap(struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.Prepare NPE Agent Bots for Team Swap // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void Reset NPE Agent Bots(bool Only Living Bots, struct UObject* __WorldContext); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.Reset NPE Agent Bots // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void Spawn NPE Agent Bot(struct FVector InLocation, struct FRotator InRotation, struct UCharacterDataAsset* InCharacter, enum class EAresTeamRole InTeamRole, bool IsAllyBot, struct TMap<enum class EAresItemSlot, struct AAresItem*> InInventoryChanges, int32_t InBotNumber, struct UObject* __WorldContext, bool& Success, struct AController_NPE_AgentBot_C*& OutNPEBotController, struct AShooterPlayerState*& OutShooterPlayerState, struct AShooterCharacter*& OutShooterCharacter); // Function FunctionLibrary_NPE_AgentBot.FunctionLibrary_NPE_AgentBot_C.Spawn NPE Agent Bot // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
};

