// BlueprintGeneratedClass MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C
// Size: 0x30 (Inherited: 0x30)
struct UMatchDetailsSharedFunctions_C : UBlueprintFunctionLibrary {

	void SetPlayerNameWithPlayerDetails(struct FPlayerDetailsDTO PlayerDetailsDTO, struct UWBP_Panel_PlayerName_C* WBP_Panel_PlayerName, struct UObject* __WorldContext); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.SetPlayerNameWithPlayerDetails // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void GetAbilityIcon(struct UCharacterUIData* CharacterUIData, enum class ECharacterAbilitySlot EquipmentSlot, struct UObject* __WorldContext, struct UTexture2D*& AbilityIcon); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetAbilityIcon // (Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetAbilityEffects(struct FAbilityEffectDTO AbilityEffectDTO, enum class ECharacterAbilitySlot EquipmentSlot, struct UObject* __WorldContext, struct TMap<struct FString, int32_t>& AbilityEffects); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetAbilityEffects // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetAbilityUsageAverage(struct TMap<struct FString, int32_t> AbilityEffects, int32_t AbilityCasts, int32_t NumRounds, struct UObject* __WorldContext, struct FText& AbilityUsageAverage); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetAbilityUsageAverage // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetPlayerCharacterUIData(struct FProcessedMatchDetails ProcessedMatchDetails, struct FString Subject, struct UObject* __WorldContext, struct UCharacterUIData*& CharacterUIData); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetPlayerCharacterUIData // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetRoundResultText(bool IsWin, struct FString Result, struct UObject* __WorldContext, struct FText& ResultText); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetRoundResultText // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetPlayerDeathmatchPlacement(struct FProcessedMatchDetails ProcessedMatchDetails, struct FString Subject, struct UObject* __WorldContext, int32_t& PlayerPlacement); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetPlayerDeathmatchPlacement // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void IsRanked(struct FProcessedMatchDetails MatchDetails, struct UObject* __WorldContext, bool& IsRanked); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.IsRanked // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void IsPremierMatch(struct FProcessedMatchDetails MatchDetails, struct UObject* __WorldContext, bool& IsPremierMatch); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.IsPremierMatch // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetRankedTierDetails(int32_t Tier, struct FProcessedSeasonInfo ProcessedSeasonInfo, struct FString Subject, struct UObject* __WorldContext, struct FMatchDetailsRankedTierDetails& MatchDetailsProgressionResults); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetRankedTierDetails // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void GetMatchHighlights(struct FName AllyTeam, struct FProcessedMatchDetails ProcessedMatchDetails, struct UObject* __WorldContext, struct FMatchDetailsMatchHighlightsResults& MatchHighlightsResults); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetMatchHighlights // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void DidMatchGoToOT(struct FProcessedMatchDetails ProcessedMatchDetails, struct UObject* __WorldContext, bool& Result); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.DidMatchGoToOT // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetHalfForRound(int32_t RoundNumber, struct FProcessedMatchDetails ProcessedMatchDetails, struct UObject* __WorldContext, enum class MatchHalf& half); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetHalfForRound // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetKDAForSubject(struct FProcessedMatchDetails ProcessedMatchDetails, struct FString Subject, struct UObject* __WorldContext, int32_t& Kills, int32_t& Deaths, int32_t& Assists, bool& Found); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetKDAForSubject // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void GetEconRatingForSubject(struct FProcessedMatchDetails ProcessedMatchDetails, struct FString Subject, struct UObject* __WorldContext, int32_t& EconRating, bool& Found); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetEconRatingForSubject // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void GetCombatScoreForSubject(struct FProcessedMatchDetails ProcessedMatchDetails, struct FString Subject, struct UObject* __WorldContext, int32_t& CombatScore, bool& Found); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetCombatScoreForSubject // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void GetPlayerHighlightsForSubject(struct FProcessedMatchDetails ProcessedMatchDetails, struct FString Subject, struct UObject* __WorldContext, int32_t& BestRound, int32_t& DamagePerRound, int32_t& FirstBloods, double& KillsPerRound, struct TMap<enum class MatchDetailsPlayerHighlightEnum, int32_t>& MultiKills, bool& Found); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetPlayerHighlightsForSubject // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	bool IsObserver(struct FProcessedMatchDetails Details, struct FString MySubject, struct UObject* __WorldContext); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.IsObserver // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	struct FText FormatGameNameAndTagLine(struct FText GameName, struct FText TagLine, struct UObject* __WorldContext); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.FormatGameNameAndTagLine // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetMatchOutcome(struct FProcessedMatchDetails ProcessedMatchDetails, struct FName MyTeamName, struct UObject* __WorldContext, enum class EMatchOutcome& Outcome); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetMatchOutcome // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetRoundSwapIndex(struct FProcessedMatchDetails MatchDetails, struct UObject* __WorldContext, int32_t& RoundSwap); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetRoundSwapIndex // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void AllianceToTeam(enum class EAresAlliance Alliance, struct FProcessedMatchDetails Details, struct FString MySubject, struct UObject* __WorldContext, struct FName& Team); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.AllianceToTeam // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetEnemyTeamDetails(struct FProcessedMatchDetails Details, struct FString MySubject, struct UObject* __WorldContext, struct FTeamDetailsDTO& Value); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetEnemyTeamDetails // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetAllyTeamDetails(struct FProcessedMatchDetails Details, struct FString MySubject, struct UObject* __WorldContext, struct FTeamDetailsDTO& Value); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetAllyTeamDetails // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetColorForTeam(struct FName Team, struct FProcessedMatchDetails Details, struct FString MySubject, struct UObject* __WorldContext, struct FSlateColor& SlateColor); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetColorForTeam // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	bool IsAllyTeam(struct FName Team, struct FProcessedMatchDetails Details, struct FString MySubject, struct UObject* __WorldContext); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.IsAllyTeam // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetAllMatchHighlights(struct FProcessedMatchDetails ProcessedMatchDetails, struct UObject* __WorldContext, struct TMap<enum class MatchDetailsHighlightEnum, struct FMatchDetailsHighlight>& BlueHighlights, struct TMap<enum class MatchDetailsHighlightEnum, struct FMatchDetailsHighlight>& RedHighlights); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetAllMatchHighlights // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void GetMVPHighlightForSubject(struct FString Subject, struct FProcessedMatchDetails ProcessedMatchDetails, struct UObject* __WorldContext, int32_t& RoundNum, int32_t& Kills, bool& Found); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetMVPHighlightForSubject // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetPlayerCountForTeam(struct FName Team, struct FProcessedMatchDetails ProcessedMatchDetails, struct UObject* __WorldContext, int32_t& PlayerCount); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetPlayerCountForTeam // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetTotalBankForTeam(struct FName Team, struct FProcessedMatchDetails ProcessedMatchDetails, int32_t Round, struct UObject* __WorldContext, int32_t& TotalLoadout1); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetTotalBankForTeam // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetTotalLoadoutForTeam(struct FName Team, struct FProcessedMatchDetails ProcessedMatchDetails, int32_t Round, struct UObject* __WorldContext, int32_t& TotalLoadout1); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetTotalLoadoutForTeam // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetTotalLoadoutForSubject(struct FString Subject, struct FProcessedMatchDetails ProcessedMatchDetailsDTO, struct UObject* __WorldContext, int32_t& TotalLoadoutValue); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetTotalLoadoutForSubject // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void GetTotalRounds(struct FProcessedMatchDetails ProcessedMatchDetailsDTO, struct UObject* __WorldContext, int32_t& TotalRounds); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetTotalRounds // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetProcessedPlayerDetailsForSubject(struct FProcessedMatchDetails ProcessedMatchDetailsDTO, struct FString Subject, struct UObject* __WorldContext, struct FProcessedPlayerDetails& ProcessedPlayerDetailsDTO, bool& Found); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetProcessedPlayerDetailsForSubject // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetTeamForSubject(struct FProcessedMatchDetails ProcessedMatchDetailsDTO, struct FString Subject, struct UObject* __WorldContext, struct FName& TeamID, bool& Found); // Function MatchDetailsSharedFunctions.MatchDetailsSharedFunctions_C.GetTeamForSubject // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
};

