// BlueprintGeneratedClass PremierSharedConfigFunctions.PremierSharedConfigFunctions_C
// Size: 0x30 (Inherited: 0x30)
struct UPremierSharedConfigFunctions_C : UBlueprintFunctionLibrary {

	void IsMultiEventTournamentsEnabled(struct UObject* __WorldContext, bool& Enabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.IsMultiEventTournamentsEnabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void IsPremierRosterViewV2Enabled(struct UObject* __WorldContext, bool& Enabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.IsPremierRosterViewV2Enabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void IsViewTeamModalEnabled(struct UAresClientGameInstance* AresClientGameInstance, struct UObject* __WorldContext, bool& IsViewTeamEnabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.IsViewTeamModalEnabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void Is Display Name V2 Scrolling Enabled(struct UAresClientGameInstance* AresClientGameInstance, struct UObject* __WorldContext, bool& IsScrollingEnabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.Is Display Name V2 Scrolling Enabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void IsPremierForcedTeamRenameEnabled(struct UAresClientGameInstance* AresClientGameInstance, struct UObject* __WorldContext, bool& IsForcedTeamRenameEnabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.IsPremierForcedTeamRenameEnabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void IsPremierTeamReportEnabled(struct UAresClientGameInstance* AresClientGameInstance, struct UObject* __WorldContext, bool& IsTeamReportEnabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.IsPremierTeamReportEnabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void Is Premier Awards Tab Content Enabled(struct UObject* __WorldContext, bool& IsPremierNewTabContentEnabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.Is Premier Awards Tab Content Enabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void IsPremierPrEnabled(struct UObject* __WorldContext, bool& IsEnabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.IsPremierPrEnabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void IsPremierHubEnabled(struct UObject* __WorldContext, bool& IsPremierHubEnabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.IsPremierHubEnabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void IsSetDefaultCustomizationEnabled(struct UObject* __WorldContext, bool& IsEnabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.IsSetDefaultCustomizationEnabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void IsRosterRestrictionsEnabled(struct UObject* __WorldContext, bool& IsEnabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.IsRosterRestrictionsEnabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x19be2f0
	void IsBONBracketEnabledForBO1(struct UObject* __WorldContext, bool& Enabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.IsBONBracketEnabledForBO1 // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void TournamentMatchupStartTimeWorkaroundEnabled(struct UObject* __WorldContext, bool& IsEnabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.TournamentMatchupStartTimeWorkaroundEnabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void LeaderboardStandingsPanelEnabled(struct UObject* __WorldContext, bool& IsEnabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.LeaderboardStandingsPanelEnabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void GetAVSLockoutDurationSeconds(struct UObject* __WorldContext, int32_t& Seconds); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.GetAVSLockoutDurationSeconds // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void IsLeaderboardThreshold_Promotion_PlayoffPlacement_Enabled(struct UObject* __WorldContext, bool& IsEnabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.IsLeaderboardThreshold_Promotion_PlayoffPlacement_Enabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void IsLeaderboardThreshold_Promotion_Rank_Enabled(struct UObject* __WorldContext, bool& IsEnabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.IsLeaderboardThreshold_Promotion_Rank_Enabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void IsLeaderboardThreshold_Playoff_Rank_Enabled(struct UObject* __WorldContext, bool& IsEnabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.IsLeaderboardThreshold_Playoff_Rank_Enabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void IsLeaderboardThreshold_Playoff_Points_Enabled(struct UObject* __WorldContext, bool& IsEnabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.IsLeaderboardThreshold_Playoff_Points_Enabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
	void IsEventLiveQueueButtonCheckEnabled(struct UObject* __WorldContext, bool& IsEnabled); // Function PremierSharedConfigFunctions.PremierSharedConfigFunctions_C.IsEventLiveQueueButtonCheckEnabled // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x19be2f0
};

